import type { IconType } from 'react-icons';
import {
  FaBolt,
  FaBrain,
  FaChartLine,
  FaDatabase,
  FaDhl,
  FaEye,
  FaFilePdf,
  FaHeartbeat,
  FaLayerGroup,
  FaMagic,
  FaMicrophone,
  FaProjectDiagram,
  FaSearch,
  FaServer,
  FaVectorSquare,
} from 'react-icons/fa';
import {
  SiAmazon,
  SiAnthropic,
  SiDirectus,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGithubactions,
  SiGooglecloud,
  SiGooglemaps,
  SiJavascript,
  SiKubernetes,
  SiLangchain,
  SiMongodb,
  SiN8N,
  SiNextdotjs,
  SiNodedotjs,
  SiOpenai,
  SiPostgresql,
  SiPosthog,
  SiPython,
  SiReact,
  SiResend,
  SiShadcnui,
  SiSocketdotio,
  SiStripe,
  SiSupabase,
  SiTailwindcss,
  SiTurborepo,
  SiTwilio,
  SiTypescript,
  SiVercel,
  SiZapier,
  SiZod,
} from 'react-icons/si';

export interface TechMeta {
  icon: IconType;
  /** Brand colour, used for the icon tint. */
  color: string;
}

/**
 * Maps the `tech` strings used in data/projects.ts to a brand icon. Anything
 * not listed falls back to a generic server glyph, so adding a new tech string
 * never breaks a card.
 */
const TECH: Record<string, TechMeta> = {
  'Next.js': { icon: SiNextdotjs, color: 'currentColor' },
  React: { icon: SiReact, color: '#61DAFB' },
  Python: { icon: SiPython, color: '#3776AB' },
  FastAPI: { icon: SiFastapi, color: '#009688' },
  Flask: { icon: SiFlask, color: 'currentColor' },
  JavaScript: { icon: SiJavascript, color: '#F7DF1E' },
  OpenAI: { icon: SiOpenai, color: '#10A37F' },
  'OpenAI Realtime API': { icon: SiOpenai, color: '#10A37F' },
  'Claude (Anthropic)': { icon: SiAnthropic, color: '#D4A27F' },
  Claude: { icon: SiAnthropic, color: '#D4A27F' },
  LangChain: { icon: SiLangchain, color: '#1C3C3C' },
  LangGraph: { icon: FaProjectDiagram, color: '#34D399' },
  TypeScript: { icon: SiTypescript, color: '#3178C6' },
  TailwindCSS: { icon: SiTailwindcss, color: '#38BDF8' },
  'Tailwind CSS': { icon: SiTailwindcss, color: '#38BDF8' },
  ShadCN: { icon: SiShadcnui, color: 'currentColor' },
  TanStack: { icon: SiReact, color: '#FF4154' },
  Supabase: { icon: SiSupabase, color: '#3ECF8E' },
  PostgreSQL: { icon: SiPostgresql, color: '#4169E1' },
  MongoDB: { icon: SiMongodb, color: '#47A248' },
  Express: { icon: SiExpress, color: 'currentColor' },
  'Node.js': { icon: SiNodedotjs, color: '#339933' },
  Zod: { icon: SiZod, color: '#3E67B1' },
  Stripe: { icon: SiStripe, color: '#635BFF' },
  'Stripe Connect': { icon: SiStripe, color: '#635BFF' },
  PostHog: { icon: SiPosthog, color: '#F54E00' },
  Resend: { icon: SiResend, color: 'currentColor' },
  Twilio: { icon: SiTwilio, color: '#F22F46' },
  'pdf-lib': { icon: FaFilePdf, color: '#F40F02' },
  Turbopack: { icon: SiTurborepo, color: '#EF4444' },
  'Trigger.dev': { icon: FaLayerGroup, color: '#A78BFA' },
  OpenRouter: { icon: SiOpenai, color: '#A855F7' },
  DataForSEO: { icon: FaChartLine, color: '#60A5FA' },
  'Google Maps API': { icon: SiGooglemaps, color: '#EA4335' },
  'Google Cloud': { icon: SiGooglecloud, color: '#4285F4' },
  'AWS EC2': { icon: SiAmazon, color: '#FF9900' },
  'AWS Lambda': { icon: SiAmazon, color: '#FF9900' },
  AWS: { icon: SiAmazon, color: '#FF9900' },
  Vercel: { icon: SiVercel, color: 'currentColor' },
  Docker: { icon: SiDocker, color: '#2496ED' },
  Kubernetes: { icon: SiKubernetes, color: '#326CE5' },
  'DHL API': { icon: FaDhl, color: '#FFCC00' },
  Directus: { icon: SiDirectus, color: '#6644FF' },
  WebSockets: { icon: SiSocketdotio, color: 'currentColor' },
  Pinecone: { icon: FaVectorSquare, color: '#60A5FA' },
  Firebase: { icon: SiFirebase, color: '#FFCA28' },
  Zapier: { icon: SiZapier, color: '#FF4F00' },
  n8n: { icon: SiN8N, color: '#EA4B71' },
  RAG: { icon: FaSearch, color: '#34D399' },
  LLM: { icon: FaBrain, color: '#10A37F' },
  LLMs: { icon: FaBrain, color: '#10A37F' },
  'Generative AI': { icon: FaMagic, color: '#A78BFA' },
  'Computer Vision': { icon: FaEye, color: '#34D399' },
  'AI / RAG': { icon: FaBrain, color: '#10A37F' },
  'Vector DBs': { icon: FaDatabase, color: '#60A5FA' },
  'Vector Search': { icon: FaDatabase, color: '#60A5FA' },
  'TTS / STT': { icon: FaMicrophone, color: '#A78BFA' },
  Vision: { icon: FaEye, color: '#34D399' },
  'CI/CD': { icon: SiGithubactions, color: '#2088FF' },
  pg_cron: { icon: SiPostgresql, color: '#4169E1' },
  Monitoring: { icon: FaHeartbeat, color: '#F87171' },
  Automation: { icon: FaBolt, color: '#FBBF24' },
  'next-safe-action': { icon: SiNextdotjs, color: 'currentColor' },
  'Multi-tenant Architecture': { icon: FaLayerGroup, color: '#60A5FA' },
};

const FALLBACK: TechMeta = { icon: FaServer, color: '#A3A3A3' };

export function getTechMeta(label: string): TechMeta {
  return TECH[label] ?? FALLBACK;
}
