import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome' }).catch(() => chromium.launch());
const p = await b.newPage({ viewport: { width: 1280, height: 1000 } });
await p.goto('https://feinwerks.software/contact', { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.waitForTimeout(2500);
console.log('lang:', await p.getAttribute('html', 'lang'));
console.log('BUTTONS:', await p.$$eval('button,[role=tab],a', ns => ns.map(n => n.innerText.trim().replace(/\s+/g,' ')).filter(Boolean).slice(0,40)));
console.log('INPUTS:', await p.$$eval('input,textarea', ns => ns.map(n => n.name + ':' + n.type + (n.hidden||n.offsetParent===null?'(hidden)':''))));
await p.screenshot({ path: 'prod-contact.png', fullPage: true });
await b.close();
