import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome' }).catch(() => chromium.launch());
const p = await b.newPage({ viewport: { width: 1280, height: 1000 } });
const r = await p.goto('https://feinwerks.software/contact', { waitUntil: 'domcontentloaded', timeout: 60000 });
console.log('status', r.status());
await p.waitForTimeout(1500);
await p.getByText(/decline|ablehnen/i).first().click().catch(() => {});
await p.getByText(/something else|etwas anderes/i).first().click();
await p.getByRole('button', { name: /continue|weiter/i }).click();
await p.waitForTimeout(600);
await p.locator('textarea[name="message"]').fill('Production pipeline check from Claude. Safe to ignore.');
await p.getByText(/not sure yet|noch unklar|noch nicht sicher/i).first().click();
await p.getByRole('button', { name: /continue|weiter/i }).click();
await p.waitForTimeout(600);
await p.locator('input[name="name"]').fill('Prod Check');
await p.locator('input[name="email"]').fill('feinwerksoftware@gmail.com');
await p.locator('button[role="checkbox"], input[name="consent"]').first().click();
await p.getByRole('button', { name: /send|senden/i }).click();
await p.waitForTimeout(8000);
const toasts = await p.locator('[data-sonner-toast]').all();
for (const t of toasts) console.log('TOAST', await t.getAttribute('data-type'), (await t.innerText()).replace(/\s+/g,' '));
console.log('sent screen:', await p.getByText(/message received|nachricht erhalten/i).isVisible().catch(() => false));
await b.close();
